name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./member/pom.xml
          mvn clean package -f ./notification/pom.xml
          mvn clean package -f ./alert/pom.xml
          mvn clean package -f ./runwayobject/pom.xml
          mvn clean package -f ./runwaycrack/pom.xml
          mvn clean package -f ./equipment analysis/pom.xml
          mvn clean package -f ./equipmentdashboard/pom.xml

      - name: Docker Build and push for Member
        uses: docker/build-push-action@v4
        with:
          context: ./member
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/member:latest
            ghcr.io/${{ github.repository }}/member:${{ github.ref_name }}
            
      - name: Docker Build and push for Notification
        uses: docker/build-push-action@v4
        with:
          context: ./notification
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/notification:latest
            ghcr.io/${{ github.repository }}/notification:${{ github.ref_name }}
            
      - name: Docker Build and push for Alert
        uses: docker/build-push-action@v4
        with:
          context: ./alert
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/alert:latest
            ghcr.io/${{ github.repository }}/alert:${{ github.ref_name }}
            
      - name: Docker Build and push for Runwayobject
        uses: docker/build-push-action@v4
        with:
          context: ./runwayobject
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/runwayobject:latest
            ghcr.io/${{ github.repository }}/runwayobject:${{ github.ref_name }}
            
      - name: Docker Build and push for Runwaycrack
        uses: docker/build-push-action@v4
        with:
          context: ./runwaycrack
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/runwaycrack:latest
            ghcr.io/${{ github.repository }}/runwaycrack:${{ github.ref_name }}
            
      - name: Docker Build and push for EquipmentAnalysis
        uses: docker/build-push-action@v4
        with:
          context: ./equipment analysis
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/equipment-analysis:latest
            ghcr.io/${{ github.repository }}/equipment-analysis:${{ github.ref_name }}
            
      - name: Docker Build and push for Equipmentdashboard
        uses: docker/build-push-action@v4
        with:
          context: ./equipmentdashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/equipmentdashboard:latest
            ghcr.io/${{ github.repository }}/equipmentdashboard:${{ github.ref_name }}
            
