apiVersion: apps/v1
kind: Deployment
metadata:
  name: runwaycrack
  labels:
    app: runwaycrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runwaycrack
  template:
    metadata:
      labels:
        app: runwaycrack
    spec:
      containers:
        - name: runwaycrack
          image: "username/runwaycrack:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
