apiVersion: apps/v1
kind: Deployment
metadata:
  name: equipment analysis
  labels:
    app: equipment analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: equipment analysis
  template:
    metadata:
      labels:
        app: equipment analysis
    spec:
      containers:
        - name: equipment analysis
          image: "username/equipment analysis:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
